# build
markdown: kramdown
permalink: /blog/:year/:title/
gems:
  - jekyll-redirect-from
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip
layouts_dir: ./_noita
sass:
  sass_dir: noita/_scss
  style: compressed
# compress layout in _noita/compress.html
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
# theme
noita:
  name: San Diego DevOps
  description: Devoted to Continuous Development in delivering reliable software
  author:
    name: 
    url: http://www.sddevops.org/
  lang: en
  favicons:
    - /assets/2014/04/21/favicon.ico
  topbar:
    toggle: Menu
    left:
      - name: About
        url: /#about
      - name: Meetings
        url: /#meetings
      - name: Slides
        url: https://github.com/sddevops/presentations
      - name: Get Involved
        url: /#involved
    class: top-bar-li 
